# Generated by Django 5.2.1 on 2025-05-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Veículo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca do Veículo')),
                ('ano', models.IntegerField(verbose_name='Ano do Veículo')),
                ('descricao', models.TextField(verbose_name='Descrição do Veículo')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
    ]
